#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

app.swagger:
  path: /doc/api.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

# A) WORKING
teamsInfo:
  path: /api/equipos
  controller: App\Controller\EquiposController::teamsInfo

#  B) WORKING
teamsInfoByName:
  path: equipos/{nombre}
  controller: App\Controller\EquiposController::teamsInfoByName

#  C) WORKING
playersTeam:
  path: equipo/jugadores
  controller: App\Controller\EquiposController::playersTeam

#  D) WORKING
playersNameByTeam:
  path: equipo/jugadores/{nombre}
  controller: App\Controller\EquiposController::playersNameByTeam

#  E) WORKING
playersInfo:
  path: jugadores
  controller: App\Controller\JugadoresController::playersInfo

#  F) WORKING
playersInfoByName:
  path: jugadores/{nombre}
  controller: App\Controller\JugadoresController::playersInfoByName

# G) WORKING
playerHighWeight:
  path: jugador/fisico/{nombre}
  controller: App\Controller\JugadoresController::playerHighWeight

# H) WORKING
playerStatistics:
  path: estadisticas/jugador/{nombre}
  controller: App\Controller\EstadisticasController::playerStatistics

# I)  WORKING
playerStatisticsAvg:
  path: estadisticas/jugador/{nombre}/avg
  controller: App\Controller\EstadisticasController::playerStatisticsAvg

# J) WORKING
localResultsByTeamName:
  path: partidos/resultados/local/{nombre}
  controller: App\Controller\PartidosController::localResultsByTeamName

# K) WORKING
visitorResultsByTeamName:
  path: partidos/resultados/visitante/{nombre}
  controller: App\Controller\PartidosController::visitorResultsByTeamName

# L) WORKING
avgReceivedPointsAsLocalByTeamName:
  path: partidos/resultados/media/local/{nombre}
  controller: App\Controller\PartidosController::avgReceivedPointsAsLocalByTeamName

# M) WORKING
avgReceivedPointsAsVisitorByTeamName:
  path: partidos/resultados/media/visitante/{nombre}
  controller: App\Controller\PartidosController::avgReceivedPointsAsVisitorByTeamName